version: "3.8"

services:
  db:
    image: postgres:18-alpine
    container_name: shorturl-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: short-url
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shorturl-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: "12345"
      DB_NAME: short-url
      DB_PORT: 5432
    depends_on:
      - db

# volumes:
#   data:
#     driver: local